### ISSUE TITLE
Implement Software Stops

### ISSUE THREAD

**Issue by arathuun** [YCPRadioTelescope/YCP-RT-ControlRoom#109]
Allow for the software stops to be designated from  ~~the limit switches,~~ the motor encoders, the motor steps, or the absolute encoders.

~~This also means that you may have to reset the encoder position if a limit switch is hit at an incorrect encoder position~~

**Comment by AktionP** [comment]
This is most likely going to be deleted, as the mechanical team is unable to work on the project

**Comment by tfranks31** [comment]
The main software stops core has been implemented and is functional. Any further changes should be addressed in new issues.
