### ISSUE TITLE
Prep cameras for Deployment

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#119]
Test all of the cameras and the NVR, as well as make sure that all of the right settings are selected such that we provide the smoothest installation experience

**Comment by AndrewGeorgiou** [comment]
Basic functionality reached; Cameras display, record, and playback video. Next step is to export video to external device.

**Comment by AktionP** [comment]
This is now up to the back end application to finish the implementation
