### ISSUE TITLE
Ensure all Data is Sent to Database

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#152]
We need to make sure that all of the data that we want to send up to the database, is actually being sent up to the database. Talk with Joel to double check that the empty tables in the local database are supposed to be empty

**Comment by kkennelly** [comment]
All data is being sent except for the vibrations table. We have decided to push this off until another semester, as it is not a high priority and requires some more calculations.
The sensor_overrides table and thresholds table are not interacting with the control room. However, my next task is to do that. Find issue #105
