### ISSUE TITLE
User validation needed for...everything

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#183]
Very few text fields have user validation, so they will all need gone through and verified that they are validating user input. Currently, if nothing is entered, or something invalid is entered, the program will crash.

Some that I noticed right off the bat are on `MainForm.cs`:
- MCU IP Address
- PLC port
- MCU Port
- Weather station COM port

**Comment by DanPalm5** [comment]
After investigation, the best course of action was to validate the input fields in MainForm AFTER pressing the finalize settings button. Implementation focus will now shift there. More to come

**Comment by DanPalm5** [comment]
Todd has stated he would like the following changes:

- Speed slider containing expected range (as opposed to slider textbox)
- Tooltips for labels containing expected values, as opposed to a message box
- Change background color to yellow or red when an invalid value is entered and disable finalize settings
- These changes should be made to both the MainForm and RTControlForm

I will begin these changes immediately!
