### ISSUE TITLE
Make emails only be sent out to admins

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#192]
Presently, email notifications are being sent out to all users, but we only want them to be sent out to the administrators that have the email option selected. In order to do this, a new `DatabaseOperations` function will have to be created to retrieve all admin users (the SQL query will have to use both the `user` and `user_role` tables).

I previously thought a new `user_role` entity would have to be created, but this may not be necessary, as the `user_role` table may be accessable through the Entity framework's `SqlQuery` syntax.

For this new function, a corresponding test will need to be added to `DatabaseOperationsTests`.

**Comment by Esherymack** [comment]
Feature is implemented on EmailNotifications4 as of today.
