### ISSUE TITLE
Send out email notification any time a push notification is sent

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#194]
In terms of when they're used, emails and push notifications are pretty similar. For example, when we set a sensor override, we want to send a push notification to notify that an override has been set, but we also want to send an email.

Basically, the user will receive an email (if they have email notifications selected on their profile) if an override is set, temperature threshold is reached, limit switch is hit (possibly outdated), and so on. A great place to start would be to look for anywhere `pushNotification.send()` is called, and also send an email in that location.

The use of push notifications and emails may be expanded in the future, but we only know what we know at the time.

**Comment by Esherymack** [comment]
Feature is implemented on EmailNotifications4 as of today.
