### ISSUE TITLE
Create Temperature tests in DatabaseOperations

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#211]
An error in temperature was caught recently in [this issue](https://github.com/YCPRadioTelescope/RT-Contracts/issues/110), which could have been caught if the Control Room had tests for the Temperature entity. All that will need added is a `TestAddAndRetrieveTemperatures` test function so we can verify that temperatures are working, and that we don't break them down the road.

**Comment by davidmchugh2000** [comment]
USE:
AddSensorData
GetTempData
