### ISSUE TITLE
Update Diagnostics Form - Sensor Data tab

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#272]
![Redesigned Sensor Data page](https://cdn.discordapp.com/attachments/625801308854812684/821563179368185866/unknown.png "Redesigned Sensor Data page")
- Remove reference to second azimuth home sensor
- Remove reference to azimuth limit switches
- Add accelerometer data
  - The dotted-line square is where the FFT visualization will be
  - Directly under, there is just enough room for a color-coded key at the bottom for x, y and z
- Rename group boxes to more-accurately describe the type of sensor data they display

### ADDITIONAL POINTS DIFFERENT FROM THE PICTURE:
- Make sure both gates are being accounted for (say "gates" instead of gate)
- Change "Current Azimuth" to "Azimuth Position"
- Say Azimuth Motor Temp and Elevation Motor Temp
- accelerometer data
  - Remove "Motor" from counterbalance
  - Don't bother with making the data update or display anything; this will be covered in a future issue

**Comment by davidmchugh2000** [comment]
Gate -> Gates

**Comment by davidmchugh2000** [comment]
"Key:"

Makes colors same as 276
