### ISSUE TITLE
Implement additional sensor overrides

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#274]
We have a lot of nice sensor overrides, but we want more to account for the Sensor Network.

The following overrides must be added to the `OverrideSwitchData` class:
- overrideAzimuthAbsEncoder
- overrideElevationAbsEncoder
- overrideAzimuthAccelerometer
- overrideElevationAccelerometer
- overrideCounterbalanceAccelerometer

Also add set methods for the above functions that we will add a `DatabaseOperations` command to, to retrieve the sensor's override using the following `SensorItemEnum` values:
- Elevation encoder: `ELEVATION_ABS_ENCODER` - must be added
- Azimuth encoder: `AZIMUTH_ABS_ENCODER` - must be added
- Azimuth motor accelerometer: `AZ_MOTOR_VIBRATION` - already exists
- Elevation motor accelerometer: `ELEV_MOTOR_VIBRATION` - already exists
- Counterbalance accelerometer: `COUNTER_BALANCE_VIBRATION` - already exists

In `RadioTelescopeController`, there is a `setOverride` function. Observe the way other overrides are being set using that, and how the strings are. The reason we take in strings is because those strings are used to send push notifications and emails. The other field is for whether we're setting the override or not. You should be fairly safe just copy-pasting and modifying one of the elements of the first if-else statement.

Now we're ready to actually hook up those new buttons to the code! In `DiagnosticsForm.cs`, look at the way the other override buttons are formatted; azimuth motor should be a good one to look at, for example. The only thing that's really changing is the string you send through to change an override, so that is safe to copy, paste and modify.

Next, take a look at the `updateButtons` function. Add five additional parameters to account for your new overrides, and then change their respective buttons' properties the same way the other ones are. This will, mostly, be copy, paste and modify.

After adding to the constructor, there should be some red on the scrollbar, pointing to the locations where this function is called; there should be two said locations. To fix these, above all the `updateButtons` calls, create bools and retrieve your override values, then pass them through as parameters.

Aaaaand, you're done! They don't actually override anything yet, but that's only because we aren't doing anything with the Sensor Network values yet.

Test this by running the GUI, open up two Diagnostics Forms, change both of them to the Sensor Overrides screen, and click all your sensor overrides slowly. You should see the other screen auto-update to the settings. If you do, then you know you've done everything correctly.

**Comment by davidmchugh2000** [comment]
Back end changes made
