### ISSUE TITLE
Add stop RT movement button on the GUI

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#291]
Right now, if the telescope is moving and we want to stop it quickly, we have to hit the red emergency stop. This is inconvenient, so the aim of this is to add such a button to the user interface so the person operating the software can also stop the telescope in its tracks.

**Comment by Liam920** [comment]
Most of this functionality is created, need to figure out a bug that is preventing the button from becoming disabled once the telescope is not moving

**Comment by Liam920** [comment]
Add confirmation to the stop button to ensure a stop is wanted
