### ISSUE TITLE
Improving UI

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#3]
We need to add more functionality into the UI, make it cleaner and add in the data from the sensors (once that is developed). We also may need to add more manual control of the telescope

**Comment by dretzlaf** [comment]
User interface has been redesigned to be more asthetically pleasing without sacraficing any functionaity implemented by the previous team. I have reorganized 3 of the forms they created and gotten rid of the manual control form based on requests by the clients. Moving forward i will be implementing the new functionality i added to the GUIs
