### ISSUE TITLE
Script to Safely Return From Software Stop

### ISSUE THREAD

**Issue by kkennelly** [YCPRadioTelescope/YCP-RT-ControlRoom#31]
Must be able safely move the telescope back from beyond the software stop, and away from the hardware stop

**Comment by jminor717** [comment]
the way the MCU handles this in hardware is by only allowing jog moves in the direction opposite the stop. we could add a check to each move commands that we send to the MCU and throw an exception if some one try's to move past or further into the stop

**Comment by AktionP** [comment]
Since this is already being done on the PLC, we can close this issue
