### ISSUE TITLE
Verify the production Weather Station still works

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#327]
We haven't tested the Weather Station in a long time, so we need to make sure that it is still working correctly. In order to do this, the assignee of this issue will need to grab it from room 118, and then test it on the latest control room build (in Development).

Refer to the general documentation regarding details about the Weather Station. If the details there are found to be insufficient, then we will need to update them.

**Comment by DanPalm5** [comment]
4/14/21 - I was able to verify that the Production Weather Station does correctly read in the values it displays on the sensor suite. **However**: the default COM port should NOT be 222 for production. You will need to go into device manager and see which port the sensor suite is using. The documentation has been updated to document this requirement. An example is below:
![image](https://user-images.githubusercontent.com/57024625/114801890-a2e5de80-9d6a-11eb-8519-2f9df44456a4.png)

We also get a bug when running the Production Weather Station for a few seconds. It will throw one of two errors (that I have experienced so far)
1) 
![image](https://user-images.githubusercontent.com/57024625/114802065-0708a280-9d6b-11eb-8ec8-d512b3ca4313.png)
2) 
![image](https://user-images.githubusercontent.com/57024625/114802075-0c65ed00-9d6b-11eb-8a7c-942751ba185c.png)

We will need to investigate the cause of this bug further.
