### ISSUE TITLE
MoveOrder.cs

### ISSUE THREAD

**Issue by lgartrell** [YCPRadioTelescope/YCP-RT-ControlRoom#332]
## Overview
This class will represent the MoveOrders that will be queued by the management thread. This class will most likely grow as we continue to diagnose the needs of the control room

## Work To Do:
- [ ] Diagnose all the class member fields needed
- [ ] Create MoveOrder.cs

**Comment by pdnelson** [comment]
This will no longer be needed because we are no longer queuing individual movements.

**Comment by pdnelson** [comment]
This will no longer be needed because we are no longer queuing individual movements.
