### ISSUE TITLE
Abstract out the MCU Monitoring Routine

### ISSUE THREAD

**Issue by lgartrell** [YCPRadioTelescope/YCP-RT-ControlRoom#333]
## Overview
At the moment, we do have the basic functionality for this built out. It just needs abstracted so that it can be used for both the homing routine, `MoveAndWaitForCompletion`, and other movement functions that are planned in the future. This does NOT include jogging. This will loop around during a movement until:
1. The Movement Completed bits are set to true and the motors are not moving
2. The `MovementInterruptFlag` flag is set `True` by a higher layer of abstraction
  - This could happen from dangerous sensor data, or a stop being issued manually from a higher-priority movement from the control room
3. MCU error bit being set

A `MovementResult` should be returned after the movement has completed. This will contain the error checking in `MoveAndWaitForCompletion`.

Calling this function might look something like this:
![image](https://user-images.githubusercontent.com/48131480/116138493-e31a5a80-a6a2-11eb-91ee-4a424958e1eb.png)

## Work To Do:
- [x] Create `MovementMonitor` method within `MCUManager.cs`. This should return a `MovementResult`.
  - [x] Include all functionality of the `MoveAndWaitForCompletion` monitoring
  - [x] Checks that the end position is correct, like in `HomeBothAxes`
- [x] Create `MovementResult.cs`. This enum should encompass the overall outcome of the MCU movement, and will be separate from the specific error register enum.
  - None
  - Completed
  - Cancelled
  - Failed
- [x] Create `MovementInterruptFlag` boolean flag. This belongs in the `MCUManager`
- [x] Learn more about additional errors. Right now, we have four error registers with five error bits each. There may be more, so this will need to be investigated. (Ask Patrick or Lucas for the MCU manual PDF).

Retries: Right now, there is no plan for retrying failed commands. If something fails, a push notification and email notification will be sent out, and the MCU will have error bits populated (depending on the error), which can be viewed on the `DiagnosticsForm`. It is then up to the user to verify that the telescope is in a safe state and can resume operation.

## Diagram of Proposed Monitoring Routine
Below is an example of what the client agreed monitoring routine should do, with the while loop making the above checks at each step.

![mcu_monitoring_routine](https://user-images.githubusercontent.com/48131540/113774276-0c277b00-96f5-11eb-94f7-092d58a0d020.png)

**Comment by pdnelson** [comment]
608d8fe939475bfc8760ee52e691b80e56ce187f

**Comment by pdnelson** [comment]
e9e16114d17c40aafa301f349f917862f6a09cc4
