### ISSUE TITLE
Add Appt Priorities

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#4]
Implement Appt Priorities and Appt Priority Logic:

Priority is appt property (Enum)

Secondary (0)
Primary (1)
Manual (2)
When getting next appt, get highest priority appt

Have thread checking for a higher appt, if one is added, stop current appt and start new appt. (using RT interrupt)

Talk to Kyle, Kate, and/or Joel with if you have questions

**Comment by TUllery** [comment]
How is this not already implemented? High priority this semester!

**Comment by pdnelson** [comment]
Just confirmed with Kyle that this one can be closed.

**Comment by pdnelson** [comment]
Commit: https://github.com/YCPRadioTelescope/YCP-RT-ControlRoom/commit/6ff63b958acc7765dc6df732b7bef5324acc722a
