### ISSUE TITLE
Allow the telescope to stow correctly even if it hasn't been homed

### ISSUE THREAD

**Issue by pdnelson** [YCPRadioTelescope/YCP-RT-ControlRoom#402]
There may be times when we need to stow the telescope and it has not been homed.

This will use the absolute encoders to determine stow position. You will have to figure out what orientation the absolute encoders are at when the telescope is in stow, and then move to that orientation.

You can use the `At_Home` MCU bit to determine whether or not you can use the offset orientations or you will have to use the un-offsetted absolute encoder values.

**Comment by DanPalm5** [comment]
We need to further investigate the issues with the absolute encoder before we can begin this issue.
