### ISSUE TITLE
Update Custom Orientation Script Range of Motion

### ISSUE THREAD

**Issue by tfranks31** [YCPRadioTelescope/YCP-RT-ControlRoom#447]
The elevation range of motion for the telescope is supposed to be -7° to 93°. Currently, the custom orientation movement script accepts a range of -15° to 93°.  This accepted range needs to be updated to the actual range of motion, -7° to 93°. The custom orientation movement script instructions should also be updated to reflect this change, as well as any associated documentation.
![Custom Orientation Degrees](https://user-images.githubusercontent.com/51765760/137951125-00e58b87-d064-4867-8d1e-e8b904873372.png)

**Comment by tfranks31** [comment]
The software-stop range will be able to be changed and enabled/disabled. The limits of the customer orientation movements should reflect that. When software-stops are enabled, the limits should be the same as the software-stop limits used by the telescope. When they are disabled, there should be either a default range allowed, no range limit, or set to the range of the limit switches. This decision should be discussed with Todd before moving forward.

**Comment by jsnyder17** [comment]
We don't need to speak with Todd. Will work on the issue
