### ISSUE TITLE
Add pop-up to confirm software-stops disable checkbox "click"

### ISSUE THREAD

**Issue by tfranks31** [YCPRadioTelescope/YCP-RT-ControlRoom#452]
Whenever disabling a safety feature, it is important to force the user to confirm that they want to disable the safety feature. Our software-stops are a safety feature and should force the user to confirm that they want to disable the software-stops. When the user clicks the checkbox to disable the software-stops, a pop-up should appear asking them to confirm that they want to disable the software-stops. Only if the user selected "Yes", the checkbox should be unchecked and the software-stops should be disabled. Otherwise, they should be left enabled.

It may be a good idea to add some sort of indicator that the software-stops are disabled as well, in case the user would forget to turn them back on. Maybe a flashing red dot or something that catches the user's eye? The indicator should be run past Todd to determine what he wants to do.

Below is the software-stops checkbox:
![Screenshot 2021-11-09 201222](https://user-images.githubusercontent.com/51765760/141399060-35dc053d-7aeb-4104-af5b-c1e89e1e1884.png)

**Comment by Bkearney1** [comment]
Addressed in
https://github.com/YCPRadioTelescope/YCP-RT-ControlRoom/commit/4b22d92d466d96a309af25e38776238592ef058d
