### ISSUE TITLE
Add a ResetMCUErrorBit RemoteListener Command

### ISSUE THREAD

**Issue by tfranks31** [YCPRadioTelescope/YCP-RT-ControlRoom#474]
After an MCU failure, resetting MCU errors is important for the telescope to perform more movements. Currently, the MCU Error Bit can be reset on the diagnostics form, and there is a label notifying the user that the MCU Error Bit is set.

Admin users should be able to reset this MCU Error Bit from their remote devices without interacting with the Control Room application manually. We need to add a new remote listener command to allow the MCU Error Bit to be reset remotely.

A couple of things to consider:
- We need to add a new TCP protocol version that offers this support
- The client connection should send a new command for resetting the bit, and when that command is received, the MCU Error Bit gets reset
- There needs to be a way for the client connections to know that the MCU Error Bit is set and needs to be reset
- If the MCU Error Bit is reset remotely, the Control Room application MCU Error Bit Set label should reflect the change
- Don't forget to add more tests!

**Comment by pdnelson** [comment]
The current MCU error bit(s) label on the Diagnostics Form updates with the most recent MCU status automatically on every tick, so you won't have to worry about manually setting it!
