### ISSUE TITLE
Change software stops to use the elevation absolute encoder

### ISSUE THREAD

**Issue by tfranks31** [YCPRadioTelescope/YCP-RT-ControlRoom#475]
So that we don't forget:

This should be as simple as replacing the `CurrentCBAccelElevationPosition` with `CurrentAbsoluteOrientation.Elevation` in the `GetSoftwareStopElevation()` method in `RadioTelescopeController.cs`. This should only be done once the elevation absolute encoder is properly working again.

**Comment by Liam920** [comment]
Should have updated these, we will just have to test this with the fixed EAE
