### ISSUE TITLE
Sensor Checking

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#52]
Need to add in the checking of all of the sensors before a script is run, to prevent any runs when situations will cause damage to telescope. As well, need to add in the overrides to these checks so that if there is a serious situation in which the telescope must move, no matter what, the clients can move the telescope to a safe position

**Comment by TUllery** [comment]
How is this not already implemented? If not, make it a high priority.

**Comment by pdnelson** [comment]
I was thinking the same thing when I saw this in the ice box, but it's likely that overrides needed to be implemented before this. Right now it looks like the only things being checked before a script is run are temperature thresholds. I'll set this as a priority.

**Comment by pdnelson** [comment]
Upon further investigation (and confirmation with Kyle), this _has_ been implemented. I must have just been looking in the wrong place for the check.

**Comment by pdnelson** [comment]
Commit: https://github.com/YCPRadioTelescope/YCP-RT-ControlRoom/commit/79b4e11a1bbb456c32dbd2413a9c78c09595a64e
