### ISSUE TITLE
PLC/MCU Info and CE/EE Design updates

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#53]
This issue is to address the connections between the CE/EE teams and the control room team.

Not much progress is expected to be made on this issue, this is simply to serve as a record for any modifications that exist within the PLC/MCU that may affect the control room application

**Comment by AktionP** [comment]
We are now grabbing the packet data for the limit switches and the proximity sensors

**Comment by AktionP** [comment]
We are grabbing the plc packet data from the simulation and the irl telescope.
There is more testing that is being done to fix a bug in displaying the packet data (limit switches and proximity sensors) on the diagnostics page.

We also need to continue to work with the VR team to have them send back the proper values at the correct positions.

**Comment by jminor717** [comment]
this fully works in production, there is still some work that needs to be done in the simulator but i'm not sure if that work falls under the this issue

**Comment by AktionP** [comment]
This is as up to date as it will be for the foreseeable future
