### ISSUE TITLE
Make email and push notifications togglable

### ISSUE THREAD

**Issue by tfranks31** [YCPRadioTelescope/YCP-RT-ControlRoom#557]
Running unit tests on a PC that can send out emails or push notifications will blast its admins with them. We should make them togglable, at least for testing, so this doesn't happen.

On top of this, it would be useful to manually toggle them from the Control Room so that testing the telescope doesn't blast out emails and push notifications.

Not sure how to do this, but I believe in you!

**Comment by jsnyder17** [comment]
it is done my lord
