### ISSUE TITLE
Validate Security Cameras

### ISSUE THREAD

**Issue by AktionP** [YCPRadioTelescope/YCP-RT-ControlRoom#82]
We need to make sure that the security cameras can be connected to our local server and display and record video feeds from all of the cameras

**Comment by AndrewGeorgiou** [comment]
We have ordered an NVR, four security cameras, and a 3TB HDD

https://amcrest.com/2mp-1080p-security-camera-system-with-4k-4ch-poe-nvr-4-x-2-megapixel-ip67-weatherproof-metal-dome-poe-ip-cameras-nv2104e-ip2m-851eb4-black.html

https://www.amazon.com/WD-Blue-3TB-Hard-Drive/dp/B013HNYV42/ref=sr_1_1?keywords=wd+blue+hdd+3TB&qid=1582137253&sr=8-1

**Comment by AktionP** [comment]
Security Cameras are functional and ready for more setup and development
